### ISSUE TITLE
Should pass duo error to the callback

### ISSUE THREAD

**Issue by sjincho** [imyelo/gulp-duojs#3]
https://github.com/imyelo/gulp-duojs/blob/master/index.js#L35

Seems like the duo error isn't passed to the callback.

**Comment by imyelo** [comment]
thanks! I released 0.4.2 for this. 
feel free to reopen this issue if it doesn't work for you! :smile:

**Comment by sjincho** [comment]
Great, thanks for the fix!

2015-08-01 2:47 GMT+09:00 yelo notifications@github.com:
